version: '3'

services:
    db:
        image: postgres
        environment:
            DB_NAME: cuebot_local
            DB_USER: cuebot
            DB_PASS: postgres
            POSTGRES_DB: cuebot_local
            POSTGRES_USER: cuebot
            POSTGRES_PASSWORD: postgres
        volumes:
            - opencue-db:/var/lib/postgresql/data
    opencue:
        image: opencue/cuebot
        command: [
            "--datasource.cueDataSource.url=jdbc:postgresql://$${DB_HOST}/$${DB_NAME}",
            "--datasource.cueDataSource.username=$${DB_USER}", 
            "--datasource.cueDataSource.password=$${DB_PASS}"
        ]
        ports:
            - "8080:80"
            - "8443:8443"
        links:
            - db:db
        environment:
            DB_HOST: db
            DB_NAME: cuebot_local
            DB_USER: cuebot
            DB_PASS: postgres
volumes:
    opencue-db:
