version: '3'

services:
    db:
        image: sirasit1234/opencue-db:init
        env_file:
            - 'opencue.env'
        volumes:
            - opencue-db:/var/lib/postgresql/data
    opencue:
        image: opencue/cuebot
        command: [
            "--datasource.cueDataSource.url=jdbc:postgresql://$${DB_HOST}/$${DB_NAME}",
            "--datasource.cueDataSource.username=$${DB_USER}", 
            "--datasource.cueDataSource.password=$${DB_PASS}"
        ]
        ports:
            - "8080:80"
            - "8443:8443"
        links:
            - db:database
        environment:
            DB_HOST: database
volumes:
    opencue-db:
